<a href="https://colab.research.google.com/github/AmyXu5523471/AmyXu5523471-AnalyticsEngineering/blob/main/maths/simple_maths.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Create Database

In [6]:
import sqlite3
import pandas as pd

# Create or connect to a database file
conn = sqlite3.connect("shop.db")
cur = conn.cursor()

print("Database connected successfully.")

Database connected successfully.

Create simple Table

In [ ]:
cur.execute("""
CREATE TABLE IF NOT EXISTS sales (
    sale_id INTEGER PRIMARY KEY AUTOINCREMENT,
    product_name TEXT,
    category TEXT,
    price REAL,
    quantity INTEGER
);
""")

conn.commit()
print("Table created.")

Table created.

Insert sample data

In [ ]:
cur.executemany("""
INSERT INTO sales (product_name, category, price, quantity)
VALUES (?, ?, ?, ?);
""", [
    ('Laptop', 'Electronics', 800, 2),
    ('Phone', 'Electronics', 500, 3),
    ('Headphones', 'Electronics', 100, 5),
    ('Desk Chair', 'Furniture', 150, 4),
    ('Desk', 'Furniture', 300, 2),
    ('Notebook', 'Stationery', 5, 20),
    ('Pen Pack', 'Stationery', 10, 10)
])

conn.commit()
print("Data inserted.")

Data inserted.

View all data

In [8]:
df = pd.read_sql_query("""
SELECT *
FROM sales;
""", conn)

df

   sale_id product_name     category  price  quantity
0        1       Laptop  Electronics  800.0         2
1        2        Phone  Electronics  500.0         3
2        3   Headphones  Electronics  100.0         5
3        4   Desk Chair    Furniture  150.0         4
4        5         Desk    Furniture  300.0         2
5        6     Notebook   Stationery    5.0        20
6        7     Pen Pack   Stationery   10.0        10

Calculate the AVG Price

In [9]:
pd.read_sql_query("""
SELECT AVG(price) AS average_price
FROM sales;

""", conn)

   average_price
0     266.428571

Calculate Total Quantity Sold

In [10]:
pd.read_sql_query("""
SELECT SUM(quantity) AS total_quantity
FROM sales;

""", conn)

   total_quantity
0              46

Calculate Highest and Lowest Price

In [12]:
pd.read_sql_query("""
SELECT
  MAX(price) as highest_prices,
  MIN(price) AS lowest_price
FROM sales;

""", conn)

   highest_prices  lowest_price
0           800.0           5.0

Calculate revenue per product

In [13]:
pd.read_sql_query("""
SELECT
    product_name,
    price,
    quantity,
    price * quantity AS revenue
FROM sales;

""", conn)

  product_name  price  quantity  revenue
0       Laptop  800.0         2   1600.0
1        Phone  500.0         3   1500.0
2   Headphones  100.0         5    500.0
3   Desk Chair  150.0         4    600.0
4         Desk  300.0         2    600.0
5     Notebook    5.0        20    100.0
6     Pen Pack   10.0        10    100.0

Calculate total revenue

In [14]:
pd.read_sql_query("""
SELECT SUM(price * quantity) AS total_revenue
FROM sales;

""", conn)

   total_revenue
0         5000.0

Calculate revenue per category

In [15]:
pd.read_sql_query("""
SELECT
    category,
    SUM(price * quantity) AS category_revenue
FROM sales
GROUP BY category;

""", conn)

      category  category_revenue
0  Electronics            3600.0
1    Furniture            1200.0
2   Stationery             200.0

Calculate average price per category

In [16]:
pd.read_sql_query("""
SELECT
    category,
    AVG(price) AS average_price
FROM sales
GROUP BY category;

""", conn)

      category  average_price
0  Electronics     466.666667
1    Furniture     225.000000
2   Stationery       7.500000

Calculate count products per category

In [18]:
pd.read_sql_query("""
SELECT
  category,
   COUNT(*) AS product_count
FROM sales
GROUP BY category

""", conn)

      category  product_count
0  Electronics              3
1    Furniture              2
2   Stationery              2

Which category has a revenue greater than 2000

In [19]:

pd.read_sql_query("""
SELECT
    category,
    SUM(price * quantity) AS category_revenue
FROM sales
GROUP BY category
HAVING SUM(price * quantity) > 2000;
""", conn)

      category  category_revenue
0  Electronics            3600.0